export const ADD_PRODUCT = "ADD_PRODUCT";
export const ADD_PRODUCT_CHEK = "ADD_PRODUCT_CHEK";
export const ADD_PRODUCT_ERROR = "ADD_PRODUCT_ERROR";

export const DOWNLOAD_PRODUCTS = "DOWNLOAD_PRODUCTS";
export const DOWNLOAD_PRODUCTS_CHEK = "DOWNLOAD_PRODUCTS_CHEK";
export const DOWNLOAD_PRODUCTS_ERROR = "DOWNLOAD_PRODUCTS_ERROR";

export const PRODUCT_DELETE = "PRODUCT_DELETE";
export const PRODUCT_DELETE_CHEK = "PRODUCT_DELETE_CHEK";
export const PRODUCT_DELETE_ERROR = "PRODUCT_DELETE_ERROR";

export const PRODUCT_EDIT = "PRODUCT_EDIT";
export const INIT_EDITION_PRODUCT = "INIT_EDITION_PRODUCT";
export const PRODUCT_EDIT_CHEK = "PRODUCT_EDIT_CHEK";
export const PRODUCT_EDIT_ERROR = "PRODUCT_EDIT_ERROR";

export const VIEW_ALERT = "VIEW_ALERT";
export const HIDE_ALERT = "HIDE_ALERT";
